midiPlayer:
  #Do not change
  version: 2
  #the category of sounds
  soundCategory: master
  #check for updates
  checkVersion: true
  #File containing instrument mapping
  map: default.map
  #File containing drum machine mapping
  drum: default.drm
